filter:
    excluded_paths:
        - tests/
checks:
    php:
        variable_existence: true
        use_statement_alias_conflict: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        switch_fallthrough_commented: true
        simplify_boolean_return: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        require_scope_for_methods: true
        require_php_tag_first: true
        remove_extra_empty_lines: true
        property_assignments: true
        precedence_mistakes: true
        precedence_in_conditions: true
        parse_doc_comments: true
        parameter_non_unique: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        overriding_private_members: true
        no_trailing_whitespace: true
        no_short_open_tag: true
        no_property_on_interface: true
        no_non_implemented_abstract_methods: true
        no_short_method_names:
            minimum: '3'
        no_goto: true
        no_error_suppression: false
        no_debug_code: true
        more_specific_types_in_doc_comments: true
        missing_arguments: true
        method_calls_on_non_object: true
        instanceof_class_exists: true
        foreach_traversable: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: false
        fix_line_ending: true
        fix_doc_comments: true
        encourage_shallow_comparison: true
        duplication: true
        deprecated_code_usage: true
        deadlock_detection_in_loops: true
        code_rating: true
        closure_use_not_conflicting: true
        closure_use_modifiable: true
        catch_class_exists: true
        avoid_duplicate_types: true
        avoid_closing_tag: false
        assignment_of_null_return: true
        argument_type_checks: true
        no_long_variable_names:
            maximum: '40'
        no_short_variable_names:
            minimum: '3'
        phpunit_assertions: true
        remove_php_closing_tag: false
        no_mixed_inline_html: false
        require_braces_around_control_structures: false
        psr2_control_structure_declaration: false
        avoid_superglobals: false
        security_vulnerabilities: false
        no_exit: false
tools:
    external_code_coverage:
        timeout: 300
build:
    image: default-bionic
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
