tools:
    external_code_coverage:
        timeout: 300
build:
    image: default-bionic
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
